---
- name: Ensure .ssh directory exists {{ item.username }}
  ansible.builtin.file:
    path: "/home/{{ item.username }}/.ssh"
    state: directory
    owner: "{{ item.username }}"
    group: "{{ item.username }}"
    mode: 0700

- name: Add public key of the {{ item.username }}
  ansible.builtin.authorized_key:
    user: "{{ item.username }}"
    key: "{{ item.ssh_key }}"
    state: present
